// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-TylIxvfSugjFKCfcg30fcddHYEy_-Ro',
    appId: '1:374285777744:android:4c1eb0ef75e6f119314a55',
    messagingSenderId: '374285777744',
    projectId: 'flutter-incoming-call',
    storageBucket: 'flutter-incoming-call.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvxUKNdbYHPn4Lzi9yPgph_1BiB8b3N64',
    appId: '1:374285777744:ios:5b4a25b310e66f28314a55',
    messagingSenderId: '374285777744',
    projectId: 'flutter-incoming-call',
    storageBucket: 'flutter-incoming-call.appspot.com',
    iosClientId:
        '374285777744-d9en0us8qbei6dka182qej82ll4pvncr.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterIncomingCall',
  );
}
